Imports DevExpress.Xpf.Core
Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Linq
Imports System.Text
Imports System.Windows.Input

Namespace DxSample.ViewModels
	Public Class MainViewModel
		Public Overridable Property Tasks() As ObservableCollection(Of Task)

		Public Overridable Property SelectedTask() As Task

		Public Sub New()
			Tasks = New ObservableCollection(Of Task)() From {
				New Task() With {
					.Title = "Read War and Peace",
					.Description="This will make me cleverer",
					.IsComplete=True
				},
				New Task() With {
					.Title = "Learn DevExress",
					.Description="This will open a lot of possibilities",
					.IsComplete=False
				},
				New Task() With {
					.Title = "Become rich",
					.Description="Just for fun",
					.IsComplete=False
				},
				New Task() With {
					.Title = "Write a book",
					.Description="This is for my soul",
					.IsComplete=False
				}
			}
		End Sub

		'CloseTaskCommand is automatically generated by the POCO mechanism
		Public Sub CloseTask(ByVal task As Task)
			Tasks.Remove(task)
		End Sub

		Public Function CanCloseTask(ByVal task As Task) As Boolean
			Return task.IsComplete
		End Function

		Public Sub AddNewTask()
			Tasks.Add(New Task() With {.Title = "New Task"})
		End Sub
	End Class

	Public Class Task
		Public Property Title() As String
		Public Property Description() As String
		Public Property IsComplete() As Boolean
	End Class
End Namespace
