using DevExpress.Xpf.Core;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Windows.Input;

namespace DxSample.ViewModels
{
    public class MainViewModel
    {
        public virtual ObservableCollection<Task> Tasks
        {
            get;
            set;
        }

        public virtual Task SelectedTask
        {
            get;
            set;
        }

        public MainViewModel()
        {
            Tasks = new ObservableCollection<Task>()
            {
                new Task(){ Title = "Read War and Peace", Description="This will make me cleverer",IsComplete=true },
                new Task(){ Title = "Learn DevExress", Description="This will open a lot of possibilities",IsComplete=false },
                new Task(){ Title = "Become rich", Description="Just for fun",IsComplete=false },
                new Task(){ Title = "Write a book", Description="This is for my soul",IsComplete=false }
            };
        }

        //CloseTaskCommand is automatically generated by the POCO mechanism
        public void CloseTask(Task task)
        {
            Tasks.Remove(task);
        }

        public bool CanCloseTask(Task task)
        {
            return task.IsComplete;
        }

        public void AddNewTask()
        {
            Tasks.Add(new Task() { Title = "New Task" });
        }
    }

    public class Task
    {
        public string Title
        {
            get;
            set;
        }
        public string Description
        {
            get;
            set;
        }
        public bool IsComplete
        {
            get;
            set;
        }
    }
}
